### ISSUE TITLE
Request for pseudo semseg and depth for IN-1k

### ISSUE THREAD

**Issue by ywwwei** [EPFL-VILAB/MultiMAE#13]
Thanks for the great work!
Could you please provide the pseudo semseg and depth for IN-1k to reproduce the result?

Thanks!

**Comment by roman-bachmann** [comment]
Hi @ywwwei!

Thank you!

We just uploaded the ImageNet-1K train and val pseudo labels for both Omnidata depth and COCO semantic segmentation. Please see the instructions [here](https://github.com/EPFL-VILAB/MultiMAE/blob/main/SETUP.md#downloadable-imagenet-1k-pseudo-labels) on how to download them. For more details, please also check out the section on which networks we used [here](https://github.com/EPFL-VILAB/MultiMAE/blob/main/SETUP.md#pseudo-labeling-networks).

Hope this helps!

Best, Roman
