### ISSUE TITLE
making 'mask_valid' folder in evaluate

### ISSUE THREAD

**Issue by jw256** [EPFL-VILAB/MultiMAE#14]
Hello! 
I just want to setup this nice work quickly, and got a problem with inference. 
I used 'run_finetuning_depth.py' trying to see the code running well, also followed 'setup.md' to download NYUv2 dataset and structure folders. 
But got not found error 'mask_valid' folder. 
How can I make the 'mask_valid' folder for evaluate only?

**Comment by roman-bachmann** [comment]
Hi @jw256!

Probably the simplest way to get the masks is to just download them from:
```
wget https://cs.nyu.edu/~deigen/dnl/normals_gt.tgz
tar xzf normals_gt.tgz
```
This way, you can simply find them inside the extracted folders as PNG files.

These 1449 images are split into 795 train and 654 test images, according to http://horatio.cs.nyu.edu/mit/silberman/indoor_seg_sup/splits.mat, which you can open with [scipy.io.loadmat](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html).

Best, Roman

**Comment by Huiimin5** [comment]
Hi,

Are you saying that the folder "mask" after data preparation (python tools/prepare_nyuv2.py) is expected to be "mask_valid" folder in run_finetuning_depth.py? 
In that case, woudl it be more clear to change "mask" here https://github.com/EPFL-VILAB/MultiMAE/blob/66910f5b5ba236f5e731883db85fe4f24ee01106/tools/prepare_nyuv2.py#L111 to "mask_valid"?
Also, the basename of test_save_path https://github.com/EPFL-VILAB/MultiMAE/blob/66910f5b5ba236f5e731883db85fe4f24ee01106/tools/prepare_nyuv2.py#L248 should also be modified from "test" to "val", right?
