### ISSUE TITLE
colab error

### ISSUE THREAD

**Issue by AnukritiSinghh** [EPFL-VILAB/MultiMAE#18]
Hello, 

Thank you for the code. However, I am not able to run this:
`!wget https://drive.switch.ch/index.php/s/RFfTZwyKROKKx0l/download` in the google colab. Can you please recheck?

Thanks

**Comment by roman-bachmann** [comment]
Hi @AnukritiSinghh!

Thanks for bringing this to our attention. There seems to be an issue with SWITCHdrive, so I reuploaded the weights. Please try replacing the lines of code that download and unzip the weights by:
`wget https://datasets.epfl.ch/vilab/iccv21/weights/omnidata_rgb2depth_dpt_hybrid.pth -P pretrained_models`

Best, Roman
