### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [EPFL-VILAB/MultiMAE#2]
Hi, would you be interested in adding MultiMAE to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by roman-bachmann** [comment]
Hi!

We would certainly be interested in adding MultiMAE to Hugging Face! We are planning to release a Colab notebook in the following days, after which we can explore creating a Hugging Face demo.

Best, Roman

**Comment by roman-bachmann** [comment]
Hi @AK391,

We released an interactive Hugging Face demo using Gradio here: https://huggingface.co/spaces/EPFL-VILAB/MultiMAE
We are simultaneously releasing a [Colab Notebook](https://colab.research.google.com/github/EPFL-VILAB/MultiMAE/blob/main/MultiMAE_Demo.ipynb) containing code to visualize the masked reconstructions, and also show how we pseudo labeled depth and semantic segmentation.

Best, Roman

**Comment by AK391** [comment]
@roman-bachmann Gradio just released v3.0 Blocks along with the Gradio Blocks Event: https://huggingface.co/Gradio-Blocks, it would be great to have a updated blocks version of this demo in the event. Thanks
