### ISSUE TITLE
is it normal to see this during finetuning?

### ISSUE THREAD

**Issue by ucalyptus2** [EPFL-VILAB/MultiMAE#22]
```
_IncompatibleKeys(missing_keys=['output_adapters.cls.norm.weight', 'output_adapters.cls.norm.bias', 'output_adapters.cls.head.weight', 'output_adapters.cls.head.bias'], unexpected_keys=[])

```

Could be happening because of deleting the output adapter. 
![image](https://user-images.githubusercontent.com/8037297/207454383-0263a840-e511-4938-abd2-9424d3f1d9f5.png)

@dmizr thank you for replying to previous issues.

**Comment by dmizr** [comment]
Hi @forkbabu ,

Yes, this is normal to see. There is no output adapter for classification during pre-training, it is only added for fine-tuning.

Best, David
