### ISSUE TITLE
OOM！It is necesarrily needed to run with 4 V100?

### ISSUE THREAD

**Issue by GuoPingPan** [EPFL-VILAB/MultiMAE#23]
It is possible to try this model with just one 2080Ti?

**Comment by GuoPingPan** [comment]
When I am using the same GPU of COLAB, it still OOM.

![image](https://user-images.githubusercontent.com/69315544/212462520-061106d4-a363-46e4-94e4-d0ecf9147076.png)

![image](https://user-images.githubusercontent.com/69315544/212463145-dbafb482-2da4-455a-ae6f-2ce383a72e87.png)

**Comment by roman-bachmann** [comment]
Hi @GuoPingPan ,

We have never tried running MultiMAE inference on a 2080Ti, but I'm pretty sure it should be possible. 

I ran our Colab notebook again front to back with the same 15GB GPU you got assigned, and it all worked without any problems. Could you try again, please?

Best, Roman
