### ISSUE TITLE
Missing NYU normals data

### ISSUE THREAD

**Issue by tyleryzhu** [EPFL-VILAB/MultiMAE#25]
Hi! it seems like the link to the NYU depth normals data https://cs.nyu.edu/~deigen/dnl/normals_gt.tgz is down. Is there an alternative mirror where we could get this data, or is it possible to run the code without it? I tried getting it from wayback machine but I get some pre-processing errors in DataAugmentationForRegression when I try to transform the masks, which leads me to believe it's a potential data issue. Thanks!

```
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src data type = 0 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by tyleryzhu** [comment]
Turns out the weights at https://web.archive.org/web/20220412033406/https://cs.nyu.edu/~deigen/dnl/normals_gt.tgz work fine, I just needed to change dataset_regression.py to have the following as it was a bool, not ints being passed in. 

```
task_dict['mask_valid'] = task_dict['mask_valid'] * 1.
task_dict = self.transform(**task_dict)
task_dict['mask_valid'] = task_dict['mask_valid'] > 0
```

**Comment by abdullahjamal** [comment]
Hi Tyler, thanks for digging into the problem. I tried adding these lines of code in dataset_regression.py file, but it always throws nan during the loss calculation. Did you change anything else besides adding these lines?
