### ISSUE TITLE
Evaluation only on 100 images?

### ISSUE THREAD

**Issue by kalyani7195** [EPFL-VILAB/MultiMAE#28]
We were looking into the depth finetuning pipeline and realized that the eval performance is based only on 100 images from the whole NYU val dataset. I am wondering why this design decision was made. Am I missing something?
Thanks,
Kalyani

**Comment by AndrewAtanov** [comment]
Hi  @kalyani7195,

This is a bug, thanks for noting! We are updating the results (they don't seem to change drastically due to this factor).

Andrei
