### ISSUE TITLE
[Inquiry] Plans to release visualization code

### ISSUE THREAD

**Issue by cyrilzakka** [EPFL-VILAB/MultiMAE#3]
Great paper! Are there plans to release the visualization code?

**Comment by roman-bachmann** [comment]
Hi @cyrilzakka, 

We just released visualization code for our pre-trained MultiMAE model in [this Colab notebook](https://colab.research.google.com/github/EPFL-VILAB/MultiMAE/blob/main/MultiMAE_Demo.ipynb). You can also check out our [Hugging Face demo](https://huggingface.co/spaces/EPFL-VILAB/MultiMAE) for a quick and easy way to play around with the model!

Best, Roman
