### ISSUE TITLE
about run_finetuning_semseg.py

### ISSUE THREAD

**Issue by Chianghui-Wong** [EPFL-VILAB/MultiMAE#4]
HI, I find that:

in MultiMae/run_finetuning_semseg.py line735
```python
seg_pred_argmax = seg_pred[:num_classes].argmax(dim=1) 
```
I think it should be
```python
seg_pred_argmax = seg_pred[:,:num_classes,:,:].argmax(dim=1) 
```

**Comment by dmizr** [comment]
Hi @Chianghui-Wong ,

Yes, you're absolutely correct, thanks for spotting this! We'll fix that right away.

Note that this bug (fortunately) does not affect any of the reported results, as we do not assign void labels to the padded values by default.
