### ISSUE TITLE
Query about data preparation for finetuning for nyuv2-depth

### ISSUE THREAD

**Issue by AntiLibrary5** [EPFL-VILAB/MultiMAE#6]
Hi,
I think the following correction holds:
Line 357 in https://github.com/EPFL-VILAB/MultiMAE/blob/main/run_finetuning_depth.py should be
```dataset_train = build_regression_dataset(args, data_path=args.train_data_path, transform=train_transform)```
instead of
```dataset_train = build_regression_dataset(args, data_path=args.data_path, transform=train_transform)```
or the argument ```train_data_path``` should be changed to ```data_path```.

Apart from that, I am trying to recreate your results on NYUv2 for depth. but the dataset preparation instructions are not clear from the instructions in SETUP.
As explained about the folder structure , where should the GT be when finetuning for depth and evaluating. Apart from that, mask_valid for fine-tuning?
```RuntimeError: Found 0 logs in subfolders of: /tmp-network/user/varora/multimae/multimae_data/train/mask_valid```

**Comment by roman-bachmann** [comment]
Hi!

Thanks for noticing! We just pushed the fix to rename the argument to `data_path`.

Regarding the dataset preparation: We structured all our datasets in the style of the usual ImageNet folder structure (train/val folders, and class folders), with the difference that we add another level of folders that specifies the modality. Therefore, try to add another folder inside `mask_valid`, that acts as the "class folder". For example, you can just call it `all`. The final structure should be `train/mask_valid/all/{images}`.

Best, Roman
